on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    services:
      # Docker-in-Docker service (allows Docker to be used inside a container)
      docker:
        image: docker:19.03.12
        options: --privileged

    steps:
    # 1. Check out the repository
    - name: Check out repository
      uses: actions/checkout@v4

    # 2. Set up Docker Buildx (this is needed for multi-platform builds)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # 3. Build the Docker image
    - name: Build the Docker image
      run: |
        cd gazebo
        docker build . --file Dockerfile --tag digitaltwin_gazebo_image:latest
           
    # 4. Clean up (remove containers and images after test)
    - name: Clean up
      run: |
        docker-compose down
        docker rmi digitaltwin_gazebo_image:latest
